### PR TITLE
Accurate pr highfreq

### PR DESCRIPTION
**Pull request by sterlingbaldwin**
Implements an additional conversion handler for the `pr` variable that uses the more accurate `pr = PRECC + PRECL` method.

### CODE REVIEW

**Comment by sterlingbaldwin** [comment]
Fixes #74

**Comment by sterlingbaldwin** [comment]
Is there any sample data available for testing? I remember writing some code to figure out the correct table at run time, but I dont know if it will work unless I can test it.

</Sterling Baldwin>

On Aug 11, 2021, at 4:41 PM, Jill Chengzhu Zhang ***@***.***> wrote:

﻿

@chengzhuzhang commented on this pull request.

________________________________

In e3sm_to_cmip/cmor_handlers/pr_highfreq_2.py<https://urldefense.us/v3/__https://github.com/E3SM-Project/e3sm_to_cmip/pull/75*discussion_r686374019__;Iw!!G2kpM7uM-TzIFchu!iG4zfSWtvf9QCo9SXV5iEI9Ft1v3fl1aS1EeaVHzs8oIZ2-pXpfF88LYnUuF-QyzrVU$>:

> @@ -0,0 +1,58 @@
+"""
+PRECL, PRECC to pr converter
+"""
+from __future__ import absolute_import, division, print_function, unicode_literals
+
+import cmor
+from e3sm_to_cmip.lib import handle_variables
+
+# list of raw variable names needed
+RAW_VARIABLES = [str('PRECC'), str('PRECL')]
+VAR_NAME = str('pr')
+VAR_UNITS = str('kg m-2 s-1')
+TABLE = str('CMIP6_day.json')


Does pr_highfreq_2 only work with daily? I think @crterai<https://urldefense.us/v3/__https://github.com/crterai__;!!G2kpM7uM-TzIFchu!iG4zfSWtvf9QCo9SXV5iEI9Ft1v3fl1aS1EeaVHzs8oIZ2-pXpfF88LYnUuFgNxBTyI$> also has PRECC and PRECL output at 3hourly. So a pr_highfreq_3 is also needed? @sterlingbaldwin<https://urldefense.us/v3/__https://github.com/sterlingbaldwin__;!!G2kpM7uM-TzIFchu!iG4zfSWtvf9QCo9SXV5iEI9Ft1v3fl1aS1EeaVHzs8oIZ2-pXpfF88LYnUuFfnhHUWQ$> toughts?

**Comment by chengzhuzhang** [comment]
@crterai Hey Chris, would you point to the high frequency precipitation data (PRECC, PRECL) for Sterling to test out? I think you have PRECT for monthly, and PRECC, PRECL for sub monthly (daily and hourly?) Please confirm..

**Comment by crterai** [comment]
@chengzhuzhang & @sterlingbaldwin - Sorry, @chengzhuzhang mentioned that she had opened an issue but I neglected to check this until now. There was a miscommunication regarding the hi-frequency output. I actually have PRECT at daily and 3-hourly time step. When I was first testing out e3sm_to_cmip I didn't realize that precip at high frequency is called pr_highfreq and hence encountered the error about requiring PRECC and PRECL. 
In any case, here are sample files on cori to test out:
Daily data
``` /global/cscratch1/sd/terai/E3SM_NGD-ATMPhys/Convection_diagnostic/PhaseII/v2plusP3/F20TR/daily_ts_rgr_tst/PRECT_19960101_20101231.nc ```
and 
3-hourly data
``` /global/cscratch1/sd/terai/E3SM_NGD-ATMPhys/Convection_diagnostic/PhaseII/v2_MG2/F20TR/threehourly_ts_rgr_tst/PRECT_20000101_20001231.nc ```

**Comment by sterlingbaldwin** [comment]
Sorry about that @crterai. So to confirm, the high freq datasets DONT need an extra PRECC + PRECL converter?

**Comment by crterai** [comment]
That's correct @ sterlingbaldwin. The high frequency precipitation data is PRECT, so I don't need the extra PRECC + PRECL converter. 
Since it sounds like there's already a converter for daily PRECT to cmor format, I think the only converter I need is for 3-hourly PRECT output, if that doesn't already exist.

**Comment by sterlingbaldwin** [comment]
if you call the package with the `--freq 3hr` argument it will use the pr_highfreq on the 3hr data, it swaps out the table for whichever one makes sense given the temporal frequency of the data.

**Comment by crterai** [comment]
Great, thanks @sterlingbaldwin!

**Comment by chengzhuzhang** [comment]
Thank you @sterlingbaldwin. @crterai sorry i misunderstood at the first place.

**Pull request closed without merging**
