### PR TITLE
fix yaml load

### LINKED ISSUE #113: Fix yaml.load for deprecated use
defaults = yaml.load(infile) without a `loader` argument was deprecated, which resulted an error @TonyB9000 reported as:
```
File "/home/bartoletti1/anaconda3/envs/warehouse/lib/python3.8/site-packages/e3sm_to_cmip/util.py", line 389, in load_handlers
    defaults = yaml.load(infile)
TypeError: load() missing 1 required positional argument: 'Loader'
```

The erroneous line is: https://github.com/E3SM-Project/e3sm_to_cmip/blob/dd9698cfef79788c0a89062c802b17c5a2225b07/e3sm_to_cmip/util.py#L387

### PR DESCRIPTION
**Pull request by chengzhuzhang**
Closes #113

### CODE REVIEW

**Comment by chengzhuzhang** [comment]
@tomvothecoder and @TonyB9000 . This PR should fix Tony's issue. Tom, it looks like wee need an rc2 for v1.8.1...

**Review by tomvothecoder — APPROVED** [review]
Looks good.

@chengzhuzhang I think we can skip `1.8.1rc2` and go with `1.8.1` because it is a one liner fix. If there are any build issues (which seems highly unlikely), it will appear in the conda-forge feedstock CI/CD for us to fix.

**Comment by chengzhuzhang** [comment]
Sounds good. Let's see @TonyB9000 's feedback, if everything goes okay, we can go ahead and do a 1.8.1 release.

**Review by TonyB9000 — COMMENTED** [review]
Looks great to me.

**Review by TonyB9000 — APPROVED** [review]

**Pull request merged**
