### PR TITLE
fixed pcode for mpas in remap

### PR DESCRIPTION
**Pull request by TonyB9000**
Changed pcode "mpaso" to "mpasocean", as it appears in the cmor handlers.

### CODE REVIEW

**Comment by chengzhuzhang** [comment]
My bad, I should have tested with ocean handlers. @TonyB9000 could you confirm if the sea-ice handlers (--var-list siconc, sitemptop, sisnmass, sitimefrac, siu, siv, sithick, sisnthick, simass ) all work okay in datasm?

**Review by xylar — APPROVED** [review]
Looks right to me.  Make sure it gets tested, though, just in case.

**Comment by TonyB9000** [comment]
Before I test in datasm, I am testing the E2C + CWL workflows using my "run_cwltool_test" script (since I can push local E2C changes and test in my "e2c_dev" environment, not wait for a release.).  It started out OK on an mpas job but eventually failed with:

cmip6_convert_fsitherm.sh: line 5: e3sm_to_cmip: command not found

I will run again to confirm.  Could be I was sleepy...

**Comment by TonyB9000** [comment]
Running OK now.  If (v2) mpas ocean test is good, I'll run a (v2) sea-ice (as many as you like :) )

**Comment by TonyB9000** [comment]
The v2 sea-ice test failed, because "Unable to find mpas_map in the input directory".  The file is there:

`v2.LR.1pctCO2_0101.mpassi.rst.0006-01-01_00000.nc`

the find-pattern in e2c util.py "find_mpas_files" for mpas_mesh reads:

`r".*mpaso.rst.\d{4}-\d{2}-\d{2}_\d{5}.nc"`

Can you see the problem? By making things clean and uniform (Running a sea-ice job?  Use the corresponding sea-ice restart - totally automatic), we run up against "Hey, you can use the ocean restart as well, so let's use that one", which breaks the uniformity.

I will reduce the pattern to

`r".*.rst.\d{4}-\d{2}-\d{2}_\d{5}.nc"`

since there is no easy way for find_mpas_files(component, path, map_path) to know if this is ocean or sea-ice at this stage, The "component" is simply the token "mpas_mesh".

**Comment by chengzhuzhang** [comment]
> `r".*.rst.\d{4}-\d{2}-\d{2}_\d{5}.nc"`

Would this cause problem if both mpaso and mpassi rst files present?

**Comment by TonyB9000** [comment]
It would find the first one that matched.  But I just tried

`pattern = r".*mpas*.rst.\d{4}-\d{2}-\d{2}_\d{5}.nc"` (at least it would have to be an mpas restart)

And it still failed to find a match. :(  Now I don't know what to do.  That pattern should match

`v2.LR.1pctCO2_0101.mpassi.rst.0006-01-01_00000.nc`

**Comment by xylar** [comment]
So `pattern = r".*mpas*.rst.\d{4}-\d{2}-\d{2}_\d{5}.nc" ` would not be safe for finding a restart for either MPAS-Ocean or MPAS-Seaice, but "pattern = r".*mpaso\.rst\.\d{4}-\d{2}-\d{2}_\d{5}.nc" should be.

**Comment by TonyB9000** [comment]
@xylar Is there some reason that `v2.LR.1pctCO2_0101.mpassi.rst.0006-01-01_00000.nc` cannot serve as the source of the mpas mesh?

My parameterization system takes the desired CMIP6 dataset_id

(e.g. CMIP6.CMIP.E3SM-Project.E3SM-2-0.1pctCO2.r1i1p1f1.SImon.siconc.gr), automatically finds the proper source E3SM native dataset_id (e.g. E3SM.2_0.1pctCO2.LR.sea-ice.native.model-output.mon.ens1), and uses the E3SM dataset id to locate the latest (warehouse, or publication) native data files.  THEN, it swaps out "model-output.mon" for "restart.fixed", and uses THAT dataset_id to locate the corresponding restart file.

Am I forced to make a special case, and swap "sea-ice" for "ocean" in that latter dataset_id.  That seems unwise, and crufty.

**Comment by TonyB9000** [comment]
So, although my system can place a "proper" restart file into the inputs directory (mpaso for ocean, mpassi for sea-ice), I cannot do so because the "find_mpas_files()" function cannot distinguish between these when needed.

That is sadness - and needs to be fixed.  I will investigate a way to add the "mpaso/mpassi" as a parameter.

**Comment by TonyB9000** [comment]
There are two options here:

**Option One**:   We edit the 34 MPAS cmor_handlers so that instead of submitting "MPAS_mesh", we have the 25 ocean submit "MPAS_oceas_mesh" and the 9 sea-ice submit "MPAS_seaice_mesh" (easy to distinguish in "find_mpas_files()").

**Option Two**:  I add a flag to my "latest_aux_datafile <cmip_dsid> (namefile|restart) `--for-e2c`" so that when ordinarily given a CMIP6 "SImon" dataset ID, the E3SM "mpassi" restart is returned, but if "--for-e2c" is supplied, it returns the "mpaso" restart.

Option One is cleaner and more uniform ... but if users are accustomed to supplying only the "mpaso" restart file, they will be disappointed when it no longer works for sea-ice (SImon) processing.

I will go with Option Two for now - under protest :)

**Comment by TonyB9000** [comment]
python latest_aux_datafile.py -d CMIP6.CMIP.E3SM-Project.E3SM-2-0.1pctCO2.r1i1p1f1.SImon.siconc.gr -a restart
/p/user_pub/e3sm/warehouse/E3SM/2_0/1pctCO2/LR/sea-ice/native/restart/fixed/ens1/v0/v2.LR.1pctCO2_0101.mpassi.rst.0006-01-01_00000.nc
python latest_aux_datafile.py -d CMIP6.CMIP.E3SM-Project.E3SM-2-0.1pctCO2.r1i1p1f1.SImon.siconc.gr -a restart --for-e2c
/p/user_pub/e3sm/warehouse/E3SM/2_0/1pctCO2/LR/ocean/native/restart/fixed/ens1/v0/v2.LR.1pctCO2_0101.mpaso.rst.0006-01-01_00000.nc

Ta Da.  (sigh)

**Comment by TonyB9000** [comment]
@chengzhuzhang The v2 SImon test was successful (using the mpassi restart - I'm sure it will work using the mpaso one).

(care to inspect?)

l```
l /p/user_pub/e3sm/bartoletti1/Pub_Work/2_PostProcess/step_tests/the_cmorized/CMIP6/CMIP/E3SM-Project/E3SM-2-0/1pctCO2/r1i1p1f1/SImon/siconc/gr/v20221101
total 63136
-rw-rw-r--. 1 bartoletti1 publishers 25869745 Nov  1 10:42 siconc_SImon_E3SM-2-0_1pctCO2_r1i1p1f1_gr_000101-005012.nc
-rw-rw-r--. 1 bartoletti1 publishers 23094366 Nov  1 11:06 siconc_SImon_E3SM-2-0_1pctCO2_r1i1p1f1_gr_005101-010012.nc
-rw-rw-r--. 1 bartoletti1 publishers 15646691 Nov  1 11:28 siconc_SImon_E3SM-2-0_1pctCO2_r1i1p1f1_gr_010101-015012.nc
```
I can use my "run_cwltool_test" on the other sea-ice (sitemptop, sisnmass, sitimefrac, siu, siv, sithick, sisnthick, simass) next.  Or I can jump to testing datasm (once I get the datasm "util.py" codes to do the same sea-ice/ocean swap for restart, passing in the "for_e2c = True" parameter.)  It embodies the same function used in latest_aux_datafile.py

**Review by chengzhuzhang — APPROVED** [review]

**Comment by TonyB9000** [comment]
@xylar Will there be a similar problem with the namefile?  For a CMIP6 sea-ice generation, I will supply the "mpaso" restart, but the "mpassi" namefile.  Any issue there?

**Comment by xylar** [comment]
@TonyB9000, that's fine.  It is very important that the namelist and steams files be specific to the component (mpaso or mpassi).  Only the restart file can be mpaso for both components.

**Comment by TonyB9000** [comment]
@xylar @chengzhuzhang OK, Squashing and Merging...

**Comment by TonyB9000** [comment]
@chengzhuzhang Note: I'll still need a new e2c release in order to test in datasm.  The 1.9.0 still has "mpaso" in place of "mpasocean".

**Comment by chengzhuzhang** [comment]
@tomvothecoder would you please help with a new release? Thank you.

**Comment by chengzhuzhang** [comment]
Agreed to both. 

We should have done 1.9.0rc1 for the latest release. Since there is already 1.9.0, we have to do 1.9.1 this time. 

Good suggestion on the second point, would you provide some instruction to Tony (and me as a backup) for releasing on conda-forge? Thank you!

**Comment by tomvothecoder** [comment]
@TonyB9000 That is a good discussion item for our next E3SM Publication Meeting, which I think is after Thanksgiving.

I sent an email on 7/21/22 that lists our options.

I am leaning towards the second option. This will keep the `cwl_workflows` version controlled alongside `datasm`, which makes the most sense (since `e3sm_to_cmip` is a standalone package).

Options | Keeping CWL workflows in the `e3sm_to_cmip` repo and bundling it in the Python package | Hosting the CWL workflows under DataSM | Hosting them in another “independent dependency” with their own git repo and conda-forge package
-- | -- | -- | --
Pros | The CWL workflows can be distributed to a broader audience by bundling the directory with the `e3sm_to_cmip` package (which has other users)Faster development and debugging cycles for the CWL workflows, since we can test local builds of `e3sm_to_cmip` with the workflows directly before merging the changes to the master branch | The CWL workflows are needed in DataSMMakes it easier to work with the CWL workflows in DataSM since it is in the same repo | Modularity with dependencies CWL workflows can be released as a data package on conda-forge, which makes them available to a broader audience
Cons | CWL workflows are technically a separate tool that depends on `e3sm_to_cmip`, so it isn’t modular to keep it in the `e3sm_to_cmip` repoCWL workflows probably aren’t being used by others outside of the E3SM Publication team right now since it requires cloning the repo or downloading the CWL workflows directory to use them | Limits distribution of the package to DataSM – the CWL workflows were never included in the `e3sm_to_cmip` Anaconda package, so I don’t think people actually used them unless they cloned the repo. | Increases development overhead because we have to manage a separate repository and package release process, then update the dependency version in other tools like DataSM  – probably not an issue if we don’t expect the CWL workflows to be updated that much
When this makes sense | If we want to keep the CWL workflows coupled with the `e3sm_to_cmip` package for ease of development, debugging, and distribution | CWL workflows are only really used by the E3SM Publication team. The CWL workflows are used only with the latest release of e3sm_to_cmip on conda-forge | The CWL workflows are considered a tool that isn’t coupled with any repository, since it depends on `e3sm_to_cmip`We intend on releasing the CWL workflows as a data package on conda-forge. We can call it `cmor_cwl_workflows` as Tony suggested, and it can be listed under the dependencies for DataSM.

**Pull request merged**
