### PR TITLE
1.5.0

### PR DESCRIPTION
**Pull request by sterlingbaldwin**
This version adds a "simple" mode for all Amon and Lmon variables that does the variable translation but doesnt require any of the CMOR metadata or tables. This version also updates the variable handlers to work with the latest version of the CMIP6 tables. Also included is a simplification of the unit conversion method, so now all 1:1 E3SM-> CMIP6 variables can be added by simply adding an entry in the default_handlers_info.yaml table.

### CODE REVIEW

**Comment by sterlingbaldwin** [comment]
Ive added a test suite that runs a year of atmosphere data and compares it to a baseline. To run it you'll need a cwl runner (I use the cwltool). You'll also need a baseline dataset. I have a baseline on acme1 under /p/user_pub/e3sm/baldwin32/e3sm_to_cmip_testing/CMIP6_sample.

The output should look like:
```bash
>> python test.py -c /p/user_pub/e3sm/baldwin32/e3sm_to_cmip_testing/CMIP6_sample/CMIP6/
============ starting CMIP6 converter ============
checking abs550aer: : 46it [00:47,  1.03s/it]
====== all variables pass zero-diff check  =======
```

**Comment by chengzhuzhang** [comment]
> Ive added a test suite that runs a year of atmosphere data and compares it to a baseline. To run it you'll need a cwl runner (I use the cwltool). You'll also need a baseline dataset. I have a baseline on acme1 under /p/user_pub/e3sm/baldwin32/e3sm_to_cmip_testing/CMIP6_sample.

Hi @sterlingbaldwin, should cwltool be included as a dependency for installing e3sm_to_cmip? Or it is only needed for running this test example?

**Comment by sterlingbaldwin** [comment]
I dont think so, the cwltool is only required to run the CWL workflows and not required by the e3sm_to_cmip package itself. The CWL workflows should be able to be run by any CWL standards compliant workflow executor. You can install the cwl dependencies by running `conda install -c conda-forge cwltool nodejs`.

**Comment by chengzhuzhang** [comment]
I'm testing the 1.5.0 branch on Cori. I tried the `--simple` option, using

`e3sm_to_cmip -v tas, prc --input /global/cfs/cdirs/e3sm/acme_diags/test_model_data_for_acme_diags/time-series/E3SM_v1_amip --output tests/ --simple`

Files were written out as `pr.nc` and `tas.nc`,
 and the attributes of the variables are all missing. 
Header of netcdf files attached:
```
(e3sm_to_cmip_07202020) chengzhu@cori06:~/tests> ncdump -h  prc.nc
netcdf prc {
dimensions:
	time = 1740 ;
	lat = 129 ;
	lon = 256 ;
variables:
	float prc(time, lat, lon) ;
		prc:_FillValue = NaNf ;
		prc:units = "kg m-2 s-1" ;
	double time(time) ;
		time:_FillValue = NaN ;
	double lat(lat) ;
		lat:_FillValue = NaN ;
	double lon(lon) ;
		lon:_FillValue = NaN ;
}
```


Ideally, we want files to be written out as:
pr_187001_201412.nc
tas_187001_201412.nc
With correct attributes of the variables.

**Comment by sterlingbaldwin** [comment]
OK, I'll add the date-stamps from the first input file and the last input file, and add code to copy over all the global attributes and each variables attributes.

**Comment by chengzhuzhang** [comment]
When supplying with cmip6-cmor-talbe options, I got following:
```
(e3sm_to_cmip_07202020) chengzhu@cori06:~> e3sm_to_cmip -v tas, prc --input /global/cfs/cdirs/e3sm/acme_diags/test_model_data_for_acme_diags/time-series/E3SM_v1_amip --output tests/cmip6_table -t ~/cmip6-cmor-tables -u e3sm_user_config_picontrol.json
[*] Writing log output to: tests/cmip6_table/converter.log [*]
[+] Running CMOR handlers in parallel
  0%|                                                                                               | 0/2 [00:00<?, ?it/s]  File "/global/homes/c/chengzhu/.conda/envs/e3sm_to_cmip_07202020/lib/python3.8/site-packages/e3sm_to_cmip/lib.py", line 76, in run_parallel
    out = res.get(9999999)
  File "/global/homes/c/chengzhu/.conda/envs/e3sm_to_cmip_07202020/lib/python3.8/site-packages/multiprocess/pool.py", line 771, in get
    raise self._value
Error sending result: '<multiprocess.pool.ExceptionWithTraceback object at 0x2aab29af92b0>'. Reason: 'PicklingError("Can't pickle <class '_cmor.CMORError'>: it's not found as _cmor.CMORError")'
[-] Error running handlers: tas prc
  0%|                                                                                               | 0/2 [00:00<?, ?it/s]

```

**Comment by sterlingbaldwin** [comment]
You need to add the full path to the Tables directory. In this case, it should probably be `~/cmip6-cmor-tables/Tables`.

**Comment by sterlingbaldwin** [comment]
I've looked into the variable attributes issue a bit, and I dont think its possible to supply the full variable attributes list without access the the metadata tables, which sort of defeats the whole point of the "simple" option.  It would be possible to do by copying all the contents from the tables variable attributes into the variable handler, but Im hesitant to do so since it would be a bunch of work and PCMDI makes changes to the tables without any notification meaning at any point the values could become incorrect. If a user wants full and complete metadata they already that that option. However, it should be easy to add the global attributes from the input files.

**Comment by golaz** [comment]
I like the proposed syntax for the simple mode above. That could be very useful. But I'm confused as to why it's not possible to have some variables attributes.

**Comment by sterlingbaldwin** [comment]
its not impossible, I would just need to copy in most of the data from the cmip6 tables into the variable handlers. I think what I should do is just take a cmip6 tables as they currently are, and store them in the resources directory. Then if the user doesnt supply their own, it can just refer to the default value. The downside of this is that the people in PCMDI make changes to the tables without any notification, so at some point the copy will become out of date.

**Comment by golaz** [comment]
I agree, just store a copy of the cmip6 tables in the resources directory and use it as default. The tables could be updated semi periodically, for example for every major release. But the user should not expect to always have the latest one unless they download them themselves and specify them on the command line.

**Comment by chengzhuzhang** [comment]
> You need to add the full path to the Tables directory. In this case, it should probably be `~/cmip6-cmor-tables/Tables`. You can check the full text of CMOR errors by looking in the cmor_logs directory.

Yeah. The incomplete path was the problem. It now works out! Thank you @sterlingbaldwin .

**Comment by chengzhuzhang** [comment]
@sterlingbaldwin I also like your idea of keeping a copy of needed data from the cmip6 table, to be used for variable attribute in `simple` mode.  I would think we don't really need to have most updated cmip table for the `simple` application.

**Comment by sterlingbaldwin** [comment]
Im converting this to a draft while I work on the additional features.

**Comment by sterlingbaldwin** [comment]
Im still working on making sure it works with all the variables, but right now the simple variables look like this:

```
netcdf clt_000101_000112 {
dimensions:
        time = 12 ;
        lat = 180 ;
        lon = 360 ;
variables:
        float clt(time, lat, lon) ;
                clt:_FillValue = 9.96921e+36f ;
                clt:standard_name = "cloud_area_fraction" ;
                clt:long_name = "Total Cloud Cover Percentage" ;
                clt:comment = "Total cloud area fraction (reported as a percentage) for the whole atmospheric column, as seen from the surface or the top of the atmosphere. Includes both large-scale and convective cloud." ;
                clt:cell_methods = "area: time: mean" ;
                clt:cell_measures = "area: areacella" ;
                clt:units = "%" ;
        double time(time) ;
                time:_FillValue = 9.96920996838687e+36 ;
        double lat(lat) ;
                lat:_FillValue = 9.96920996838687e+36 ;
        double lon(lon) ;
                lon:_FillValue = 9.96920996838687e+36 ;

// global attributes:
                :ne = 30 ;
                :np = 4 ;
                :Conventions = "CF-1.0" ;
                :source = "CAM" ;
                :case = "20180129.DECKv1b_piControl.ne30_oEC.edison" ;
                :title = "UNSET" ;
                :logname = "golaz" ;
                :host = "nid05376" ;
                :Version = "$Name$" ;
                :revision_Id = "$Id$" ;
                :initial_file = "20171228.beta3rc13_1850.ne30_oECv3_ICG.edison.cam.i.0331-01-01-00000.nc" ;
                :topography_file = "/project/projectdirs/acme/inputdata/atm/cam/topo/USGS-gtopo30_ne30np4_16xdel2-PFC-consistentSGH.nc" ;
                :time_period_freq = "month_1" ;
                :history = "Tue Jul 21 14:52:43 2020: /export/baldwin32/projects/e3sm_to_cmip/e3sm_to_cmip/__main__.py --input /p/user_pub/e3sm/baldwin32/workshop/tutorial/180x360-mon/ --output /p/user_pub/e3sm/baldwin32/workshop/tutorial/cmiplike -v clt --simple --serial\nTue Jul 21 12:56:02 2020: ncks -t 1 -O --fl_fmt=netcdf4_classic --no_tmp_fl --dfl_lvl=1 --hdr_pad=10000 --map=/export/zender1/data/maps/map_ne30np4_to_cmip6_180x360_aave.20181001.nc --rgr no_stagger 180x360-mon/CLDTOT_000101_000112.nc 180x360-mon/CLDTOT_000101_000112_cmip6_180x360_aave.nc\nTue Jul 21 12:56:00 2020: ncrcat -O -v CLDTOT --fl_fmt=netcdf4_classic --no_tmp_fl --dfl_lvl=1 --hdr_pad=10000 atm-mon-raw/20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0001-01.nc atm-mon-raw/20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0001-02.nc atm-mon-raw/20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0001-03.nc atm-mon-raw/20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0001-04.nc atm-mon-raw/20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0001-05.nc atm-mon-raw/20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0001-06.nc atm-mon-raw/20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0001-07.nc atm-mon-raw/20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0001-08.nc atm-mon-raw/20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0001-09.nc atm-mon-raw/20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0001-10.nc atm-mon-raw/20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0001-11.nc atm-mon-raw/20180129.DECKv1b_piControl.ne30_oEC.edison.cam.h0.0001-12.nc 180x360-mon/CLDTOT_000101_000112.nc" ;
                :NCO = "netCDF Operators version 4.9.3 (Homepage = http://nco.sf.net, Code = http://github.com/nco/nco)" ;
                :map_file = "/export/zender1/data/maps/map_ne30np4_to_cmip6_180x360_aave.20181001.nc" ;
                :input_file = "180x360-mon/CLDTOT_000101_000112.nc" ;
}```

**Comment by chengzhuzhang** [comment]
Hi @sterlingbaldwin, looking at the meta data. The time coordinate could be a concern. It doesn't seem time coordinate is set properly in the generated time series.

**Comment by sterlingbaldwin** [comment]
You were correct Jill, xarray was incorrectly decoding the time axis. It was also dropping the lon/lat bounds and time_bnds so I added them back in too. here's what the updated header looks like:

```
netcdf clt_000101_000112 {
dimensions:
        time = UNLIMITED ; // (12 currently)
        lat = 180 ;
        lon = 360 ;
        nbnd = 2 ;
variables:
        float clt(time, lat, lon) ;
                clt:_FillValue = 9.96921e+36f ;
                clt:standard_name = "cloud_area_fraction" ;
                clt:long_name = "Total Cloud Cover Percentage" ;
                clt:comment = "Total cloud area fraction (reported as a percentage) for the whole atmospheric column, as seen from the surface or the top of the atmosphere. Includes both large-scale and convective cloud." ;
                clt:cell_methods = "area: time: mean" ;
                clt:cell_measures = "area: areacella" ;
                clt:units = "%" ;
        double time(time) ;
                time:_FillValue = 9.96920996838687e+36 ;
                time:long_name = "time" ;
                time:units = "days since 0001-01-01 00:00:00" ;
                time:calendar = "noleap" ;
                time:bounds = "time_bnds" ;
        double lat(lat) ;
                lat:_FillValue = 9.96920996838687e+36 ;
                lat:long_name = "Latitude of Grid Cell Centers" ;
                lat:standard_name = "latitude" ;
                lat:units = "degrees_north" ;
                lat:axis = "Y" ;
                lat:valid_min = -90. ;
                lat:valid_max = 90. ;
                lat:bounds = "lat_bnds" ;
        double lon(lon) ;
                lon:_FillValue = 9.96920996838687e+36 ;
                lon:long_name = "Longitude of Grid Cell Centers" ;
                lon:standard_name = "longitude" ;
                lon:units = "degrees_east" ;
                lon:axis = "X" ;
                lon:valid_min = 0. ;
                lon:valid_max = 360. ;
                lon:bounds = "lon_bnds" ;
        double lat_bnds(lat, nbnd) ;
                lat_bnds:_FillValue = 9.96920996838687e+36 ;
                lat_bnds:long_name = "Gridcell latitude interfaces" ;
        double lon_bnds(lon, nbnd) ;
                lon_bnds:_FillValue = 9.96920996838687e+36 ;
                lon_bnds:long_name = "Gridcell longitude interfaces" ;
        double time_bnds(time, nbnd) ;
                time_bnds:_FillValue = 9.96920996838687e+36 ;
                time_bnds:long_name = "time interval endpoints" ;

**Comment by sterlingbaldwin** [comment]
For reference, here's the header from the corresponding CMIP6 variable, the only difference I see is the fillValue, which CMIP6 decided to set as 1e20. The defauly netCDF4 fillValue for doubles is 9.96920996838687e+36 which is why thats what shows up in the "simple" output. I dont think this should be an issue, but let me know if it should be changed.

```
netcdf clt_Amon_E3SM-1-0_piControl_r1i1p1f1_gr_000101-002512 {
dimensions:
        time = UNLIMITED ; // (300 currently)
        lat = 180 ;
        lon = 360 ;
        bnds = 2 ;
variables:
        double time(time) ;
                time:bounds = "time_bnds" ;
                time:units = "days since 0001-01-01 00:00:00" ;
                time:calendar = "noleap" ;
                time:axis = "T" ;
                time:long_name = "time" ;
                time:standard_name = "time" ;
        double time_bnds(time, bnds) ;
        double lat(lat) ;
                lat:bounds = "lat_bnds" ;
                lat:units = "degrees_north" ;
                lat:axis = "Y" ;
                lat:long_name = "Latitude" ;
                lat:standard_name = "latitude" ;
        double lat_bnds(lat, bnds) ;
        double lon(lon) ;
                lon:bounds = "lon_bnds" ;
                lon:units = "degrees_east" ;
                lon:axis = "X" ;
                lon:long_name = "Longitude" ;
                lon:standard_name = "longitude" ;
        double lon_bnds(lon, bnds) ;
        float clt(time, lat, lon) ;
                clt:standard_name = "cloud_area_fraction" ;
                clt:long_name = "Total Cloud Cover Percentage" ;
                clt:comment = "Total cloud area fraction for the whole atmospheric column, as seen from the surface or the top of the atmosphere. Includes both large-scale and convective cloud." ;
                clt:units = "%" ;
                clt:cell_methods = "area: time: mean" ;
                clt:cell_measures = "area: areacella" ;
                clt:missing_value = 1.e+20f ;
                clt:_FillValue = 1.e+20f ;

**Comment by chengzhuzhang** [comment]
@sterlingbaldwin Thank you! The new meta data looks good. Just to clarify, another difference of `--simple` mode versus default is that, all the variables have a flat structure. While in the default mode, variables are places in CMIP directory structures?

**Comment by sterlingbaldwin** [comment]
Thats correct, without information such as the experiment_id, realization number, and activity_id, all normally supplied by the user metadata, its impossible to construct the correct CMIP6 directory structure. That said, it would be possible to put the output in something that mimics the structure. For example, I could setup the Amon/CFmon/Lmon directories with the per-variable subdirectories.

**Comment by chengzhuzhang** [comment]
Thanks for the clarification. I think a flat structure is good for now in the `simple` option.

**Comment by sterlingbaldwin** [comment]
@chengzhuzhang I've added support for the Lmon variables as well as added warning to the unsupported ocean variables. I can add support for additional variables in the future, right now nearly all the Amon and Lmon variables work (only pfull and phalf are unsupported for simple conversion). The Omon and SImon variables will take significant additional and I havent implemented them yet but can in the future if there is a need.

**Comment by sterlingbaldwin** [comment]
@golaz @chengzhuzhang I believe this PR is feature complete, and ready for the next round of feedback. I havent yet included the mpas variables since its a bit more complicated then the atmos/land variables, but if its something needed I can get started on them.

**Comment by chengzhuzhang** [comment]
@sterlingbaldwin Thanks. I think support for atmos/land variables are good for now. I briefly looked at the code structure. This PR looks good to me. Just one more question, handlers for some variables (i.g., clt.py) are deleted, from master. I couldn't find where the conversion is happening in 1.5.0. I may miss it somewhere, would you point it out?

**Comment by sterlingbaldwin** [comment]
@chengzhuzhang This is the biggest code-structure improvement in this version, all 2d and model-level 3d variables that are 1:1 conversions between E3SM and CMIP6 variables can now be handled using the default handler. It currently supports 4 types of unit conversion, "1-to-%", "g-to-kg", "m/s-to-kg/ms", and "-1". I tried to make it as easy as possible to add new conversions if there are more to add in the future, see: https://github.com/E3SM-Project/e3sm_to_cmip/pull/54/files#diff-ac329e39e22dae4c39495970c534e4ddR12

and 

https://github.com/E3SM-Project/e3sm_to_cmip/pull/54/files#diff-8a1a74b6fd93c7586621453928f009bdR56

This PR got a lot bigger then I was expecting, but it actually removes a bunch of handler modules, for example all the land carbon variables are now converted to the default hander, so in the future adding more variables should be as easy as adding an entry in the default_handler_info.yaml file.

**Pull request merged**
