### PR TITLE
Data stager

### PR DESCRIPTION
**Pull request by lukaszlacinski**
The data stager downloads zstash tarballs and extract data data files that match specified components and files patterns. It also extracts a restart and namelist file, and create a manifest file. Then, it transfers the files to a specified Globus endpoint.

### CODE REVIEW

**Comment by rpwagner** [comment]
@lukaszlacinski thanks for getting this in. Can you add an example usage call to the readme? And is it possible to add the [Native App Login](https://pypi.org/project/fair-research-login/) package to the requirements instead of the boilerplate login code?

**Comment by lukaszlacinski** [comment]
I updated the PR to use FAIR Native Login instead of Globus SDK for OAuth2 token handling. also extended README.md.

**Comment by rpwagner** [comment]
@sterlingbaldwin can you or someone you recommend try this out?

**Comment by sterlingbaldwin** [comment]
WIll do. I didnt see that the PR had been opened, I'll give it a shot.

**Comment by sterlingbaldwin** [comment]
Probably out of scope of this PR, but is there any way to get the correct versions of the globus-sdk and fair-native-login through conda instead of having to use pip?

**Comment by sterlingbaldwin** [comment]
@lukaszlacinski after running the steps to create a new environment, and running `pip install globus-sdk fair-native-login` I get the following message (running on cori), 

```bash
(zstash_env) sbaldwin@cori06:~/projects/testing_stager/scripts> pip install globus-sdk fair-native-login
Collecting globus-sdk
  Using cached https://files.pythonhosted.org/packages/be/c1/ccf8e8ebeb229887e6355e87e9cc9f07e06b1661b3c6e50311566bae9f28/globus_sdk-1.8.0-py2.py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement fair-native-login (from versions: none)
ERROR: No matching distribution found for fair-native-login
```

**Comment by rpwagner** [comment]
We should be able to use conda, I think @NickolausDS already made a conda package for the login code.

**Comment by NickolausDS** [comment]
Change fair-native-login --> fair-research-login and it should work.

Fair Research Login is available on pypi and conda:
* pip install fair-research-login
* conda install -c conda-forge fair-research-login

**Comment by lukaszlacinski** [comment]
@sterlingbaldwin I removed pip (replaced PyPi packages with Conda ones). Reflected it in scripts/README.md.

**Comment by sterlingbaldwin** [comment]
Thanks, I'll setup a test case and give it a shot.

**Comment by sterlingbaldwin** [comment]
@lukaszlacinski how much work do you think it would be to create a manifest file (just a simple file with one line per data file, with the file name and hash) and send it along with the data? The md5 hash values for the files are all stored in the zstash database so wouldnt need to be recomputed and the data can be validated.

**Comment by rpwagner** [comment]
@sterlingbaldwin around line 227 in the current version it creates a JSON manifest file similar to the [remote file manifest in BDBag](https://github.com/fair-research/bdbag/blob/master/doc/config.md#remote-file-manifest). That could be changed to a flat file. I'd suggest relative file path, size in bytes, and checksum. The name of the file should indicate what the checksum algorithm is (e.g., `manifest-md5.txt` to keep stealing from BagIt).

**Comment by sterlingbaldwin** [comment]
First shot I got this:
```bash
python data_stager.py -d 6961c792-3262-11ea-b95e-0e16720bb42f:/p/user_pub/e3sm/baldwin32/testing -z /home/t/tang30/2018/E3SM_simulations/repaired/20180215.DECKv1b_abrupt4xCO2.ne30_oEC.edison -c river -w 6
Traceback (most recent call last):
  File "data_stager.py", line 331, in <module>
    main(args)
  File "data_stager.py", line 209, in main
    failures = multiprocess_extract(args.workers, matches, True, True)
TypeError: multiprocess_extract() takes 3 positional arguments but 4 were given
```
I'll try again without the -w option.

**Comment by golaz** [comment]
Interesting work. I wonder whether some of that functionality should eventually be also incorporated directly into zstash itself. That possibility has been discussed under

https://github.com/E3SM-Project/zstash/issues/21

For now, @forsyth2 has implemented an option to archive lo local files only, but an extension to remote storage via globus could be useful (for both archiving and extracting).

**Comment by rpwagner** [comment]
One route that could make the Globus integration into zstash fairly quick would be to have zstash create [BDBags](https://github.com/fair-research/bdbag), with [remote references to files via Globus](https://github.com/fair-research/bdbag/blob/master/doc/config.md#remote-file-manifest). The BDBag could be sent to another system and then pull the files over Globus.

Mostly, BDBag would provide a way to do ship around manifest and groups of files with somebody else maintaining a tool to do the checking. Either way, we're glad to help with this.

**Comment by sterlingbaldwin** [comment]
@rpwagner I assume that the BDBag would be fine with https links through globus, but dont you have to do extra setup to get that to work? I.e. all files available on globus arent by default available via an https link right? Passing around bdbag remote-manifests would be the ideal.

**Comment by rpwagner** [comment]
The remote manifest supports Globus URIs, like `"uri": "globus://<endpoint>/<folder/<file>"`. So the manifest could be create with references to the staged files (or files on any endpoint). The BDBag utility looks for the Globus SDK and tokens in its keychain then submits a transfer.

**Comment by rpwagner** [comment]
And, we have a service that you can send a link to the BDBag, a destination endpoint and path, and it will submit the transfer for you. So the BDBag is generally useful, and you can use it pull files in various ways.

**Comment by sterlingbaldwin** [comment]
Attempt number two without the workers flag:

```bash
python data_stager.py -d 6961c792-3262-11ea-b95e-0e16720bb42f:/p/user_pub/e3sm/baldwin32/testing -z /home/t/tang30/2018/E3SM_simulations/repaired/20180215.DECKv1b_abrupt4xCO2.ne30_oEC.edison -c river
ERROR: Transferring file from HPSS: 000056.tar
Traceback (most recent call last):
  File "data_stager.py", line 331, in <module>
    main(args)
  File "data_stager.py", line 211, in main
    failures = extractFiles(matches, True)
  File "/global/homes/s/sbaldwin/.conda/envs/data_stager_env/lib/python3.7/site-packages/zstash-0.3.0-py3.7.egg/zstash/extract.py", line 264, in extractFiles
  File "/global/homes/s/sbaldwin/.conda/envs/data_stager_env/lib/python3.7/site-packages/zstash-0.3.0-py3.7.egg/zstash/hpss.py", line 66, in hpss_get
Exception
```

**Comment by sterlingbaldwin** [comment]
Trying again trying to pull out the 'atm' component instead of the 'river' data:

```bash
>>> python data_stager.py -d 6961c792-3262-11ea-b95e-0e16720bb42f:/p/user_pub/e3sm/baldwin32/testing -z /home/t/tang30/2018/E3SM_simulations/repaired/20180215.DECKv1b_abrupt4xCO2.ne30_oEC.edison -c atm  
Traceback (most recent call last):
  File "data_stager.py", line 331, in <module>
    main(args)
  File "data_stager.py", line 143, in main
    cur.execute(u"select value from config where arg=?", (attr,))
sqlite3.DatabaseError: database disk image is malformed```

**Comment by lukaszlacinski** [comment]
> Attempt number two without the workers flag:
> 
> ```shell
> >>> python data_stager.py -d 6961c792-3262-11ea-b95e-0e16720bb42f:/p/user_pub/e3sm/baldwin32/testing -z /home/t/tang30/2018/E3SM_simulations/repaired/20180215.DECKv1b_abrupt4xCO2.ne30_oEC.edison -c river
> ERROR: Transferring file from HPSS: 000056.tar
> Traceback (most recent call last):
>   File "data_stager.py", line 331, in <module>
>     main(args)
>   File "data_stager.py", line 211, in main
>     failures = extractFiles(matches, True)
>   File "/global/homes/s/sbaldwin/.conda/envs/data_stager_env/lib/python3.7/site-packages/zstash-0.3.0-py3.7.egg/zstash/extract.py", line 264, in extractFiles
>   File "/global/homes/s/sbaldwin/.conda/envs/data_stager_env/lib/python3.7/site-packages/zstash-0.3.0-py3.7.egg/zstash/hpss.py", line 66, in hpss_get
> Exception
> ```

The exception is thrown when zstash module runs the hsi command and the command fails. If you set:
```
export LOGLEVEL=DEBUG
```
zstash module will log errors from hsi command to see why it failed.

**Comment by lukaszlacinski** [comment]
> Trying again trying to pull out the 'atm' component instead of the 'river' data:
> 
> ```shell
> >>> python data_stager.py -d 6961c792-3262-11ea-b95e-0e16720bb42f:/p/user_pub/e3sm/baldwin32/testing -z /home/t/tang30/2018/E3SM_simulations/repaired/20180215.DECKv1b_abrupt4xCO2.ne30_oEC.edison -c atm  
> Traceback (most recent call last):
>   File "data_stager.py", line 331, in <module>
>     main(args)
>   File "data_stager.py", line 143, in main
>     cur.execute(u"select value from config where arg=?", (attr,))
> sqlite3.DatabaseError: database disk image is malformed```
> ```

The index database (zstash/index.db) might have been damaged. I would delete it after each run.

**Comment by lukaszlacinski** [comment]
> First shot I got this:
> 
> ```shell
> >>> python data_stager.py -d 6961c792-3262-11ea-b95e-0e16720bb42f:/p/user_pub/e3sm/baldwin32/testing -z /home/t/tang30/2018/E3SM_simulations/repaired/20180215.DECKv1b_abrupt4xCO2.ne30_oEC.edison -c river -w 6
> Traceback (most recent call last):
>   File "data_stager.py", line 331, in <module>
>     main(args)
>   File "data_stager.py", line 209, in main
>     failures = multiprocess_extract(args.workers, matches, True, True)
> TypeError: multiprocess_extract() takes 3 positional arguments but 4 were given
> ```
> 
> I'll try again without the -w option.

The bug has been fixed. The conda package provides a 7 month old version of the function when the function had only three arguments.

**Comment by sterlingbaldwin** [comment]
OK, running again. This time I ran into a new issue, not a show stopper but it should be fixed. 

```bash
>>> python ~/projects/testing_stager/scripts/data_stager.py -d 6961c792-3262-11ea-b95e-0e16720bb42f:/p/user_pub/e3sm/baldwin32/testing -z /home/t/tang30/2018/E3SM_simulations/repaired/20180215.DECKv1b_abrupt4xCO2.ne30_oEC.edison -c river -w 6
ERROR: The destination endpoint is not active. Please go to https://app.globus.org/file-manager/collections/9d6d99eb-6d04-11e5-ba46-22000b92c6ec to activate the endpoint.
```
Note that the destination endpoint UUID isnt whats shown in the link, but instead its the source endpoint (which was activated before running this command). The destination _did_ need to be activated, but the link shown goes to the source endpoint.

**Comment by sterlingbaldwin** [comment]
OK, so I think NERSC was killing my jobs yesterday because of disk space quotas. After cleaning a bunch of stuff out, things are working just fine today. The files are getting pulled out of the archive correctly, moved over just fine, and the inclusion of the manifest is great! My suggestions: 

1) Add a cleanup option, to remove all the files pulled from HPSS from the source if both the blocking flag is set, and the transfer task complete successfully. This is especially important on NERSC where we have pretty tight space restrictions.

2) Add a label option, which is used by the globus transfer, as well as the file manifest. For example if I was moving some atmos files from cori to compy, I might add the label "piControl-atmos," and have the manifest get named "piContorl-atmos-manifest.json". Im open to suggestions on other solutions, but without something like this the manifest from two transfers will over write each other if sent to the same destination directory, also I like to use descriptive labels for my globus transfers, since otherwise its impossible to know where the heck the files went (no way to tell from the web UI what was in the transfers or where the destination on the filesystem was).

**Comment by sterlingbaldwin** [comment]
@lukaszlacinski One more thing that just came up in a meeting yesterday. Can you add an 'all' option? This should pull out the complete archive for the given case and move it without extracting the files from the tar archives.

**Comment by sterlingbaldwin** [comment]
This is working for me, so Im going to merge it now and we can add more features later if we need them. Thanks for the work on this, it should save a lot of time.

**Pull request merged**
