### PR TITLE
PR #83 Fix high freq cwl (review fixes)

### PR DESCRIPTION
**Pull request by tomvothecoder**
Summary of Changes
* Update logic in `get_year()` in `find_start_end.cwl` to parse the correct regex pattern for years (monthly and sub-monthly)
* Update `discover_atm_files` to parse the correct files for their absolute paths to return `atm_files` list
* Revert changes related to https://github.com/E3SM-Project/e3sm_to_cmip/commit/b54dea7af29202fab6f2b5895fa69e7b7c31aca2#diff-9cc8b4180a30ce9a2a9dd6676bc74fd450b01f055d677e3a59005c305bea0bd7
   *  `pr_highfreq` should not be defined as default handler because it is not listed in `CMIP6_day.json`. 
* Remove `rlut_highfreq` from `default_handler_info.yaml` and add `rlut_highfreq.py`, which is based on `rlut.py` with some minor tweaks

### CODE REVIEW

**Comment by chengzhuzhang** [comment]
Hey, Tom. Thanks! I will test this PR by postprocess and publish a set of pr (daily highfrequency) data. We can merge this PR after sharing with @msahn to verify.

**Comment by chengzhuzhang** [comment]
I have a problem about how to proceed. e3sm_to_cmip is a dependency of esgfpub. I assume i should install the esgfpub env and then update by installing this e3sm_to_cmip branch within that env?

**Comment by tomvothecoder** [comment]
@chengzhuzhang If you're attempting to test this branch for `e3sm_to_cmip` through `esgfpub`, then that sounds exactly right.

```
cd esgfpub
conda env create -n esgfpub_dev_custom -f conda/dev.yml

conda activate esgfpub_dev_custom
cd e3sm_to_cmip
git checkout <this branch>

# This will overwrite the existing `e3smhttps://github.com/E3SM-Project/esgfpub/blob/master/conda/dev.yml_to_cmip=1.7.3` installation with the branch version 
python setup.py install
```

**Comment by chengzhuzhang** [comment]
the pr_highfreq variable generated successfully. 

But rlut_highfreq won't create. I have errors as follows:

after fixing https://github.com/E3SM-Project/e3sm_to_cmip/blob/788dec4d1691f580845d0d6772812e73bd76428b/e3sm_to_cmip/resources/default_handler_info.yaml#L299 by using `CMIP_day.json`
```
[-] No table exists for rlut_highfreq at freq day
[-] No handlers loaded
```

I get following:
```
[-] Variable rlut_highfreq is not included in table CMIP6_day.json
[-] No handlers loaded
```
So it sounds like there needs to be a `rlut_highfreq.py` handler that functions similar as `pr_highfreq`, except that `rlut` is a direct convert from `FLUT`.  Not sure if its a good idea to generate a new PR, would you help make this change on your fork?

To testing this new variable, just to change two lines in the same atm-high-freq-job.yaml:
```
# list if E3SM raw variable names
std_var_list: [FLUT]

# list of CMIP6 variable names
std_cmor_list: [rlut_highfreq]
```

**Comment by tomvothecoder** [comment]
@chengzhuzhang I've removed `rlut_highfreq` from `default_handler_info.yaml` and added `rlut_highfreq.py`.

Diff here: https://github.com/E3SM-Project/e3sm_to_cmip/pull/84/commits/6af2bdb33a31a69a183f0ca43f7e03b0a8d9a9ca

With those changes, I ran `atm-highfreq-job.yaml` with the below settings:
>``` 
># list if E3SM raw variable names
>std_var_list: [FLUT]
>
># list of CMIP6 variable names
>std_cmor_list: [rlut_highfreq]
>```

On the last step, I am getting this error:
```
INFO [workflow ] starting step step_std_cmor
INFO [step step_std_cmor] start
INFO [job step_std_cmor] /tmp/jgsjy8x2$ srun \
    -A \
    e3sm \
    --partition \
    debug \
    -t \
    2:00:00 \
    e3sm_to_cmip \
    --serial \
    --freq=day \
    --output-path \
    /tmp/jgsjy8x2 \
    --var-list \
    rlut_highfreq \
    --input-path \
    . \
    --user-metadata \
    /p/user_pub/e3sm/baldwin32/resources/CMIP6-Metadata/E3SM-1-0/piControl_r1i1p1f1.json \
    --num-proc \
    12 \
    --tables-path \
    /home/vo13/cmip6-cmor-tables/Tables/
[*] Writing log output to: /tmp/jgsjy8x2/converter.log
[+] Running CMOR handlers in serial
Error could not convert data to a numpy array
rlut: time 0.0 - 730.0:   0%|          | 0/730 [00:00<?, ?it/s]
Error could not convert data to a numpy array
rlut: time 730.0 - 1460.0:   0%|          | 0/730 [00:00<?, ?it/s]
Error could not convert data to a numpy array
rlut: time 1460.0 - 2190.0:   0%|          | 0/730 [00:00<?, ?it/s]
Error could not convert data to a numpy array
rlut: time 2190.0 - 2920.0:   0%|          | 0/730 [00:00<?, ?it/s]
Error could not convert data to a numpy array
[+] 1 of 1 handlers complete
rlut: time 2920.0 - 3650.0:   0%|          | 0/730 [00:00<?, ?it/s]
INFO [job step_std_cmor] Max memory used: 6MiB
ERROR [job step_std_cmor] Job error:
("Error collecting output for parameter 'cmip6_dir':\nscripts/cwl_workflows/atm-highfreq/cmor.cwl:57:7: Did not find output file with glob pattern: '['CMIP6']'", {})
WARNING [job step_std_cmor] completed permanentFail
ERROR [step step_std_cmor] Output is missing expected field file:///home/vo13/tomvothecoder/e3sm_to_cmip/scripts/cwl_workflows/atm-highfreq/atm-highfreq.cwl#step_std_cmor/cmip6_dir
WARNING [step step_std_cmor] completed permanentFail
INFO [workflow ] completed permanentFail
{
    "cmorized": null
}
```

Do we need to change any of these settings?
```
# horizontal regridding file path
hrz_atm_map_path: /home/zender1/data/maps/map_ne30np4_to_cmip6_180x360_aave.20181001.nc

# path to CMOR case metadata
metadata_path: /p/user_pub/e3sm/baldwin32/resources/CMIP6-Metadata/E3SM-1-0/piControl_r1i1p1f1.json
```

**Comment by tomvothecoder** [comment]
> I'm looking into this error specifically: Error could not convert data to a numpy array.
I'm thinking it is related to the data in this chunk of code:
https://github.com/tomvothecoder/e3sm_to_cmip/blob/6af2bdb33a31a69a183f0ca43f7e03b0a8d9a9ca/e3sm_to_cmip/cmor_handlers/rlut_highfreq.py#L17-L24

I fixed this issue. I was supposed to pass `data["FLUT"].values` to `cmor.write()`, not `data`.
The workflow was successful afterwards. Let me know how it goes if you test these changes.

**Comment by chengzhuzhang** [comment]
This is great! Thank you, Tom. Just checked the data look right. I think we can merge this PR now.

**Review by chengzhuzhang — APPROVED** [review]

**Pull request merged**
