### PR TITLE
Add QA tools and VSCode config

### LINKED ISSUE #127: Add quality assurance tools for robust code development

### PR DESCRIPTION
**Pull request by tomvothecoder**
- Closes #127
- Add `pyproject.toml` for `black`, and `setup.cfg` for `flake8`, `isort` `mypy` and `pytest`
- Rename `test.py` to `branch_comparison.py`
- Add placeholder test for `pytest`
- Add VSCode configs under `.vscode`
- Add `pre-commit` for optional checks before committing

### CODE REVIEW

**Comment by tomvothecoder** [comment]
FYI @chengzhuzhang  and @TonyB9000, I updated `e3sm_to_cmip` to include QA tools in the conda dev env.

You will need to pull the latest `master` and update your env using `conda env update -n e3sm_to_cmip -f conda-env/dev.yml` to get these tools installed in your dev env.

I opened up #133 to format and lint the repo using the QA tools.

**Comment by TonyB9000** [comment]
Are these to be pulled in parallel:
git clone https://github.com/E3SM-Project/e3sm_to_cmip
git clone https://github.com/E3SM-Project/esgfpub.git
(Why does one say ".git" and the other not?)
After the "-n e3sm_to_cmip" (will there be a "_prod", or only "dev"), if the warehouse needs to call e2c, don't we also need to issue (env:  psm_dev) "pip install ." (in e2c).

**Comment by tomvothecoder** [comment]
@TonyB9000 This PR is specific to `e3sm_to_cmip` repo, so you don't need to do anything with the `esgfpub` repo.

**RE:  (Why does one say ".git" and the other not?)**

Where did you copy first command? If you copy it from GitHub, it automatically adds `.git` to the end. I haven't tried it without the `.git`, but it might work.

image

**RE: After the "-n e3sm_to_cmip" (will there be a "_prod", or only "dev"), i**

Correction: `conda env update -n e3sm_to_cmip_dev -f conda-env/dev.yml`

**RE: don't we also need to issue (env: psm_dev) "pip install ." (in e2c).**

I suggested that we no longer use the workflow involving the installation of a local build of `e3sm_to_cmip` into `esgfpub` envs because it is non-deterministic. 

The only time (that I can think of) where `e3sm_to_cmip` changes affect `esgfpub` is if we release a new version of `e3sm_to_cmip`. We just need to update the listed version of `e3sm_to_cmip`  in the `esgfpub` conda env(s).

Example: https://github.com/E3SM-Project/esgfpub/blob/dcd2e14b053fb10404c69442368162f77897989d/conda-env/dev.yml#L29

**Comment by TonyB9000** [comment]
Note that the PSM employs the cwl_workflows that reside in /p/user_pub/e3sm/staging/resource/cmor/cwl_workflows/*/*.cwl

Sterling applies these in work "surrounding" the call to "e3sm_to_cmip".  He used to reference them directly by his clone of e2c, but I copied them to our operational "staging/resource" (from e3sm_to_cmip/scripts/cwl_workflows).  I'd like to change some of them, as they reference "maps" as "grids" on occasion.  In any case, any change to e2c should require re-establishing that staging/resource directory.

Does this make sense?

**Pull request merged**
