### PR TITLE
Bump to 1.8.1

### PR DESCRIPTION
**Pull request by tomvothecoder**
Action Items
- [x] Validate source code works (without new warnings) with latest version of xarray (0.21.1) and Dask (2022.1.1) by running a few workflows
  - Workflow 1: `/e3sm_to_cmip/scripts/cwl_workflows/lnd-elm/lnd-job.yaml`
  - Workflow 2: `/e3sm_to_cmip/scripts/cwl_workflows/atm-unified-eam/atm-unified-job.yaml`
 - [x] Fix `out_land_file` ref in `lnd-elm/lnd-job.yaml`

### CODE REVIEW

**Comment by xylar** [comment]
@tomvothecoder, did something create the `v1.8.1` tag and then did you delete is?  I'm trying to understand how this got triggered and how testing passed, but why I can't find a `v1.8.1` tag or release yet here?
https://github.com/conda-forge/e3sm_to_cmip-feedstock/pull/18

**Comment by tomvothecoder** [comment]
> did something create the v1.8.1 tag and then did you delete is? 

Hey @xylar, I didn't see a v1.8.1 tag created and I didn't delete it if it did exist.

To clarify, this is PR is in a draft state while we test `e3sm_to_cmip` with the latest version of xarray. Once it checks out, I will merge this PR and perform a GH release subsequently. I'll tag to update the PR you made to the feedstock.

**Comment by xylar** [comment]
@tomvothecoder, I don't see how the PR on conda-forge would have been created unless a tag was made here.  The CI there also would not have succeeded if the code weren't available under that tag.  So this is very odd indeed.  But as long as you're confident that no such tag ever existed, I'll let it be and we'll clean things up once the tag is really there.

**Comment by xylar** [comment]
The mystery is why this code exists: https://github.com/E3SM-Project/e3sm_to_cmip/archive/v1.8.1.tar.gz

**Comment by tomvothecoder** [comment]
@xylar The branch for this PR is the same name as the tag (`v1.8.1`), so maybe this causes issues in git and you're actually getting the `tar.gz` of the branch?

Usually I delete the branch after merging the PR and before creating the GH release/tag, so we might not have ran into any issues until now.

Also, I think I remember getting a warning for creating a branch that had the same name as a git tag/release.
In any case, I will stop naming the branch the same as the tag by removing the `v`.

**Comment by xylar** [comment]
I wondered about that.  I think it's fine to have a branch with that name *if* it's on your own fork, but it seems to be problematic if it's on the main repo.  I'm still surprised to learn that tags and branches both produce tarballs that are in the same location.  That seems messy!

**Pull request merged**
