### PR TITLE
Bump to 1.9.1

### PR DESCRIPTION
**Pull request by tomvothecoder**
Also update nco to 5.1.1 in dev env.

### CODE REVIEW

**Comment by chengzhuzhang** [comment]
Maybe it should be 1.9.1rc1?

**Comment by tomvothecoder** [comment]
Hmmm good point @chengzhuzhang, we still have a month of testing for E3SM-unified.

I'll revert this commit on `master` (bad practice but we're ok since I just merged and nobody probably pulled) and bump to v1.9.1rc1.

**Comment by chengzhuzhang** [comment]
Thank you!

**Comment by tomvothecoder** [comment]
Reverted this merge on `master` and superceded by #161

**Pull request merged**
