### PR TITLE
update license info in default_metadata.json

### PR DESCRIPTION
**Pull request by TonyB9000**

### CODE REVIEW

**Review by chengzhuzhang — APPROVED** [review]

**Comment by chengzhuzhang** [comment]
Hey Tony. Please don't merge this PR yet. I found that change of license will trigger cmor validation error, because v1 was registered with a different license.

**Review by chengzhuzhang — APPROVED** [review]
This PR slipped. @TonyB9000 Please merge if it is still relevant.

**Comment by TonyB9000** [comment]
@chengzhuzhang I'll need to look at this more carefully tomorrow.  I will clone the existing repo, and do a file-by-file compare to the "deployed" metadata (/p/user_pub/e3sm/staging/resource/CMIP6-Metadata/).  I want to be sure of any differences.

**Comment by TonyB9000** [comment]
Ack!  When I did a fresh "git clone", nothing of the E3SM-2-0 appeared.  Have we never pushed the 2-0 metadata to master?  I cannot believe that.  Also, the "template.json" is out-of-date (and not version-specific), but I updated it to have the current license and 2022 references.

**Comment by TonyB9000** [comment]
(Sigh)  This is e2c repo, not the metadata repo!  When I saw "default_metadata.json" I assumed the latter.

Making more work for myself :(

**Pull request merged**
